local FishList = {
    {
        id = "SunriseTrout",
        displayName = "Sunrise Trout",
        rarity = "Common",
        locations = { "Shores", "River" },
        MinorFreq = 0.9,
        MinorDist = 0.9,
        MajorFreq = 0.9,
        MajorDist = 0.9,
        chanceMultiplier = 1.1,
        luckBias = 0.6,
        value = 6,
    },
    {
        id = "AzureMinnow",
        displayName = "Azure Minnow",
        rarity = "Common",
        locations = { "Shores" },
        MinorFreq = 1,
        MinorDist = 0.8,
        MajorFreq = 1,
        MajorDist = 0.8,
        chanceMultiplier = 1,
        luckBias = 0.4,
        value = 4,
    },
    {
        id = "Glintfin",
        displayName = "Glintfin",
        rarity = "Uncommon",
        locations = { "Shores", "Deep" },
        MinorFreq = 1.05,
        MinorDist = 1.05,
        MajorFreq = 1.05,
        MajorDist = 1.05,
        chanceMultiplier = 1,
        luckBias = 0.5,
        value = 12,
    },
    {
        id = "Stormray",
        displayName = "Stormray",
        rarity = "Rare",
        locations = { "Deep" },
        MinorFreq = 1.1,
        MinorDist = 1.2,
        MajorFreq = 1.15,
        MajorDist = 1.2,
        chanceMultiplier = 0.8,
        luckBias = 0.8,
        value = 24,
    },
    {
        id = "RiverLancer",
        displayName = "River Lancer",
        rarity = "Uncommon",
        locations = { "River" },
        MinorFreq = 1.05,
        MinorDist = 1.1,
        MajorFreq = 1.05,
        MajorDist = 1.05,
        chanceMultiplier = 0.95,
        luckBias = 0.55,
        value = 14,
    },
    {
        id = "CelestEel",
        displayName = "Celest Eel",
        rarity = "Epic",
        locations = { "Deep", "River" },
        MinorFreq = 1.2,
        MinorDist = 1.2,
        MajorFreq = 1.2,
        MajorDist = 1.25,
        chanceMultiplier = 0.35,
        luckBias = 1,
        value = 42,
    },
}

return FishList
