local BlackLeg = {
    PartyTableKick = {
        Hits = 10,
        Duration = 2.4,
        DamagePerHit = 15,
        StunDuration = 0.75,
        Startup = 1.3,
        HyperArmor = false,
        Cancelable = false,
        GuardBreak = false,
        Endlag = 1.3,
        HitboxDuration = 0.1,
        Cooldown = 12,
        KnockbackDirection = "AwayFromAttacker",
        Hitbox = {
            Size = Vector3.new(7, 8, 8),
            Offset = CFrame.new(0, 0, 0),
            Duration = 0.1,
            Shape = "Cylinder",
        },
        Sound = {
            Hit = { Id = "rbxassetid://122809552011508", Pitch = 1, Volume = 1 },
            Miss = { Id = "rbxassetid://135883654541622", Pitch = 1, Volume = 1 },
            Loop = { Id = "rbxassetid://118537831520752", Pitch = 1, Volume = 1 },
        },
    },
    PowerKick = {
        Damage = 50,
        StunDuration = 1.5,
        Startup = 0.4,
        HyperArmor = false,
        GuardBreak = true,
        PerfectBlockable = true,
        Endlag = 0.5,
        HitboxDuration = 0.2,
        Cooldown = 12,
        Hitbox = {
            Size = Vector3.new(6, 6, 6),
            Offset = CFrame.new(0, 0, -3.5),
            Duration = 0.2,
            Shape = "Block",
        },
        Sound = {
            Hit = { Id = "rbxassetid://118765157785806", Pitch = 1, Volume = 1 },
        },
    },
    Concasse = {
        Damage = 75,
        StunDuration = 1.5,
        Startup = 0,
        HyperArmor = false,
        GuardBreak = false,
        PerfectBlockable = true,
        Endlag = 0,
        Range = 65,
        -- Constant travel speed for consistent feel across distances
        TravelSpeed = 65,
        HitboxDuration = 0.1,
        Cooldown = 12,
        Hitbox = {
            Size = Vector3.new(8, 8, 8),
            Offset = CFrame.new(0, 0, 0.0),
            Duration = 0.1,
            Shape = "Cylinder",
        },
        Sound = {},
    },
}

return BlackLeg
