local accent = Color3.fromRGB(91, 211, 255)

return {
    ScreenGui = {
        Name = "FishingMinigame",
        DisplayOrder = 50,
    },
    Root = {
        Enabled = true,
        BackgroundTransparency = 1,
        AspectRatio = 16 / 9,
    },
    Container = {
        Size = UDim2.fromScale(0.6, 0.22),
        AnchorPoint = Vector2.new(0.5, 1),
        Position = UDim2.fromScale(0.5, 0.9),
        BackgroundColor3 = Color3.fromRGB(12, 18, 30),
        BackgroundTransparency = 0.12,
        CornerRadius = UDim.new(0, 12),
        Padding = UDim.new(0, 12),
    },
    CaptureTrack = {
        Size = UDim2.fromScale(0.78, 0.42),
        AnchorPoint = Vector2.new(0.5, 0.5),
        Position = UDim2.fromScale(0.43, 0.5),
        BackgroundColor3 = Color3.fromRGB(21, 32, 48),
        BackgroundTransparency = 0.05,
        CornerRadius = UDim.new(0, 10),
        Stroke = {
            Thickness = 2,
            Color = Color3.fromRGB(40, 58, 82),
            Transparency = 0.15,
        },
    },
    CaptureZone = {
        WidthScale = 0.25,
        HeightScale = 0.85,
        VerticalOffset = 0,
        BackgroundColor3 = Color3.fromRGB(95, 179, 122),
        BackgroundTransparency = 0.05,
        CornerRadius = UDim.new(0, 8),
        Stroke = {
            Thickness = 2,
            Color = Color3.fromRGB(135, 227, 180),
            Transparency = 0.15,
        },
    },
    FishMarker = {
        WidthScale = 0.05,
        HeightScale = 0.85,
        VerticalOffset = 0,
        BackgroundColor3 = Color3.fromRGB(255, 200, 64),
        BackgroundTransparency = 0,
        CornerRadius = UDim.new(0, 8),
        Stroke = {
            Thickness = 1,
            Color = Color3.fromRGB(255, 226, 150),
            Transparency = 0.15,
        },
    },
    ProgressMeter = {
        Size = UDim2.fromScale(0.55, 0.08),
        AnchorPoint = Vector2.new(0.5, 0.5),
        Position = UDim2.fromScale(0.5, 0.14),
        BackgroundColor3 = Color3.fromRGB(18, 28, 44),
        BackgroundTransparency = 0.05,
        CornerRadius = UDim.new(0, 8),
    },
    ProgressFill = {
        HeightScale = 0.7,
        AnchorPoint = Vector2.new(0, 0.5),
        Position = UDim2.fromScale(0.05, 0.5),
        BackgroundColor3 = accent,
        BackgroundTransparency = 0,
        CornerRadius = UDim.new(0, 8),
    },
    ProgressLabel = {
        Enabled = true,
        Size = UDim2.fromScale(0.3, 0.06),
        AnchorPoint = Vector2.new(0.5, 0.5),
        Position = UDim2.fromScale(0.87, 0.48),
        Font = Enum.Font.GothamBold,
        TextColor3 = Color3.fromRGB(255, 255, 255),
        TextScaled = true,
        Text = "Reel In",
        BackgroundTransparency = 1,
    },
    DebugPanel = {
        Enabled = true,
        Size = UDim2.fromScale(0.22, 0.12),
        AnchorPoint = Vector2.new(0, 0),
        Position = UDim2.fromScale(0.02, 0.15),
        BackgroundColor3 = Color3.fromRGB(10, 14, 22),
        BackgroundTransparency = 0.15,
        CornerRadius = UDim.new(0, 10),
        Padding = UDim.new(0, 8),
        Title = {
            Font = Enum.Font.GothamBold,
            TextColor3 = Color3.fromRGB(255, 255, 255),
            TextSize = 18,
            BackgroundTransparency = 1,
            Text = "Hooked Fish",
        },
        Body = {
            Font = Enum.Font.Gotham,
            TextColor3 = Color3.fromRGB(220, 230, 255),
            TextSize = 14,
            BackgroundTransparency = 1,
        },
    },
}
